# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  release:
    types: [created]

jobs:

  releases-matrix:
    name: Release Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        cmd: [netdata-dash, netdata-dash-agent, netdata-dash-client]
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, "386"]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        pre_command: export CGO_ENABLED=0 && export GODEBUG=http2client=0
        ldflags: "-s -w"
        project_path: ./cmd/${{ matrix.cmd }}
        binary_name: ${{ matrix.cmd }}
        extra_files: LICENSE README.md
